version: '3.1'

services:

  db:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_DATABASE: 'mysql'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'user'
      MYSQL_ROOT_PASSWORD: 'admin'
    ports:
      - "3306:3306"
    volumes:
      - ./data/conf.d:/etc/mysql/conf.d
      - ./data/logs:/logs
      - /usr/local/var/mysql:/var/lib/mysql
